[package]
name = "so-o-basico"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["Eduardo Bonachela"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "^0.1.10"